[package]
name = "bevy_tween"
description = "Flexible tweening plugin library for Bevy"
version = "0.2.0"
edition = "2021"
authors = [ "Multirious" ]
license = "MIT OR Apache-2.0" 
repository = "https://github.com/Multirious/bevy_tween"
homepage = "https://github.com/Multirious/bevy_tween"
documentation = "https://docs.rs/bevy_tween"
readme = "README.md"
keywords = [ "bevy", "tween", "tweening", "easing", "animation" ]
categories = [ "game-development" ]

[workspace]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.0", default-features = false }

[dev-dependencies]
bevy-inspector-egui = "0.23"
bevy = { version = "0.13.0", default-features = false, features = [ "bevy_asset", "bevy_render", "bevy_sprite", "tonemapping_luts", "png" ] }
rand = "0.8.5"

[features]
default = [
  "span_tween",
  "bevy_asset",
  "bevy_render",
  "bevy_sprite"
]

# Tweener implementation by defining a tween in range of time.
span_tween = []

# Adds tweening systems for asset
bevy_asset = [ "bevy/bevy_asset" ]
# Adds nothing just yet but required by the "bevy_sprite" feature.
bevy_render = [ "bevy/bevy_render"]
# Add some built-in interpolator related to sprite
bevy_sprite = [ "bevy/bevy_sprite", "bevy_render" ]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "animated_banner"
required-features = [
  "bevy_sprite",
  "bevy_asset",
  "span_tween",
  "bevy/bevy_winit",
]

[[example]]
name = "animated_logo"
required-features = [
  "bevy_sprite",
  "span_tween",
  "bevy/bevy_winit",
]

[[example]]
name = "demo_follow"
required-features = [
  "bevy_sprite",
  "bevy_asset",
  "span_tween",
  "bevy/bevy_winit",
]

[[example]]
name = "demo_click"
required-features = [
  "bevy_sprite",
  "bevy_asset",
  "span_tween",
  "bevy/bevy_winit",
]

[[example]]
name = "span_tween"
path = "examples/span_tween/span_tween.rs"
required-features = [
  "span_tween",
  "bevy/bevy_winit",
]

[[example]]
name = "span_tween_builder"
path = "examples/span_tween/span_tween_builder.rs"
required-features = [
  "span_tween",
  "bevy/bevy_winit",
]


[[example]]
name = "quick_span_tween"
path = "examples/span_tween/quick_span_tween.rs"
required-features = [
  "span_tween",
  "bevy/bevy_winit",
]
