name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [stable, nightly]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      
    - name: Install Bevy dependencies
      if: runner.os == 'linux'
      run: sudo apt-get update; sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
      
    - name: Install cargo commands
      run: cargo install cargo-all-features
      
    - name: Check all features
      run: cargo check-all-features
      
    - name: Run tests
      run: cargo test --verbose
